# Generated by Django 5.0.6 on 2024-07-05 05:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id_genero', models.AutoField(db_column='idgenero', primary_key=True, serialize=False)),
                ('genero', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id_tour', models.AutoField(db_column='idtour', primary_key=True, serialize=False)),
                ('nombre_tour', models.CharField(max_length=20)),
                ('tipo_tour', models.CharField(max_length=20)),
                ('fecha_de_tour', models.DateField()),
                ('precio', models.IntegerField()),
                ('cantidad_personas', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('rut', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20)),
                ('apellido_paterno', models.CharField(max_length=20)),
                ('apellido_materno', models.CharField(max_length=20)),
                ('fecha_nacimiento', models.DateField()),
                ('telefono', models.CharField(max_length=12)),
                ('email', models.EmailField(blank=True, max_length=100, null=True, unique=True)),
                ('direccion', models.CharField(blank=True, max_length=50, null=True)),
                ('password', models.CharField(max_length=30)),
                ('id_genero', models.ForeignKey(db_column='idgenero', on_delete=django.db.models.deletion.CASCADE, to='core.genero')),
            ],
        ),
    ]
