# Generated by Django 5.0.6 on 2024-07-19 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_carritoitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='tours/'),
        ),
    ]
